#!/bin/sh

set -e

echo "Running postrm for request sink with $1"
if [ "$1" = 'remove' ]; then
  # remove the installation folder
  rm -rf /opt/ether/
  # remove the link in /bin
  rm -f /bin/ether
fi

exit 0
