#!/bin/sh

set -e

echo "Running postinst for ether with $1"
if  [ "$1" = configure ]; then
  # creating a link, so the application can be called from the command line
  ln -sf /opt/ether/bin/Ether /bin/ether
fi

exit 0
